mappings:
  DpsPxPayPayment_Handler: Sunnysideup\PaymentDps\Control\DpsPxPayPaymentHandler
  DpsPxPayStoredPayment_Handler: Sunnysideup\PaymentDps\Control\DpsPxPayStoredPaymentHandler
  PxPayMessage: Sunnysideup\PaymentDps\Thirdparty\PxPayMessage
  PxPayResponse: Sunnysideup\PaymentDps\Thirdparty\PxPayResponse
  MifMessage: Sunnysideup\PaymentDps\Thirdparty\MifMessage
  PxPayRequest: Sunnysideup\PaymentDps\Thirdparty\PxPayRequest
  PxPayCurl: Sunnysideup\PaymentDps\Thirdparty\PxPayCurl
  DpsPxPayStoredPayment: Sunnysideup\PaymentDps\DpsPxPayStoredPayment
  DpsPxPost: Sunnysideup\PaymentDps\DpsPxPost
  DpsPxPayComs: Sunnysideup\PaymentDps\DpsPxPayComs
  DpsPxPayPayment: Sunnysideup\PaymentDps\DpsPxPayPayment
  DpsPxPayStoredCard: Sunnysideup\PaymentDps\Model\DpsPxPayStoredCard
