---
Name: payment_dps_main
---
Sunnysideup\PaymentDps\Control\DpsPxPayPaymentHandler:
  url_segment: dpspxpaypayment
Sunnysideup\PaymentDps\Control\DpsPxPayStoredPaymentHandler:
  url_segment: dpspxpaystoredpayment
